visible_gpus : -1
temp_dir : './tmp/'
test_from: None
max_pos : 512
large : False
finetune_bert: True
encoder: bert
share_emb: False
dec_layers: 6
dec_dropout: 0.2
dec_hidden_size: 768
dec_heads: 8
dec_ff_size: 2048
enc_hidden_size: 512
enc_ff_size: 512
enc_dropout: 0.2
enc_layers: 6

ext_dropout: 0.2
ext_layers: 2
ext_hidden_size: 768
ext_heads: 8
ext_ff_size: 2048

accum_count: 1
save_checkpoint_steps: 5

generator_shard_size: 32
alpha: 0.6
beam_size: 5
min_length: 15
max_length: 150
max_tgt_len: 140
block_trigram: True

model_path: ./tmp_model/
result_path: ./tmp_result/src
recall_eval: False
report_every: 1